# Generated by Django 4.1.2 on 2023-06-24 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_secondmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstmodel',
            name='created_at',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstmodel',
            name='updated_at',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='firstmodel',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
