# Generated by Django 4.1.2 on 2023-06-24 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_firstmodel_created_at_firstmodel_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='firstmodel',
            name='updated_at',
        ),
    ]
