# Generated by Django 4.1.2 on 2023-06-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_firstmodel_created_at_firstmodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstmodel',
            name='publish',
            field=models.DateField(blank=True, null=True),
        ),
    ]
