# Generated by Django 4.1.2 on 2023-06-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_firstmodel_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
